apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivanov-bot
  namespace: ivanov-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ivanov-bot
  template:
    metadata:
      labels:
        app: ivanov-bot
    spec:
      containers:
      - name: bot
        image: cr.yandex/crp0r20ste42tqg4q7ep/currency-bot:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: bot-service
  namespace: ivanov-ns
spec:
  type: ClusterIP
  selector:
    app: ivanov-bot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
